export enum Configuration {
  TOKEN_EXPIRATION_TIME = 'TOKEN_EXPIRATION_TIME',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  SECRET_KEY_JWT= 'SECRET_KEY_JWT',
  MAIL_HOST= 'MAIL_HOST',
  MAIL_PORT= 'MAIL_PORT',
  MAIL_USER= 'MAIL_USER',
  MAIL_PASSWORD= 'MAIL_PASSWORD',
}
